version: '3.0'

services:
    web:        
        image: eliharper/lights_ui:latest
        ports: 
            - "8080:8080"
        labels:
            kompose.service.expose: "true"
            kompose.service.type: nodeport

    api:
        image: eliharper/lights_api:latest
        ports:
            - "5001:5000"

    db:
        image: mongo:latest
        ports: 
            - "27017:27017"

