version: '3.0'

services:
    web:
        image: localhost:5000/lights_ui
        ports: 
            - "8085:8080"
    api:
        image: localhost:5000/lights_api
        ports:
            - "5001:5000"
    
